# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push events for the dev branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so marp-action can access it
      - uses: actions/checkout@v2

      - name: Setup Source
        run: mkdir docs && cp os-lecs.md docs/index.md && cp -r lec[1-9]* docs && cp course-intro.md docs/course-intro.md

      - name: Marp Build (docs folder)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: --html -I docs/ -o build/
        env:
          MARP_USER: root:root

      - name: copy imgs
        run: cp -r lec[1-9]*/figs build/

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
      
